volumes:
  esdata:
    name: esdata
  kibanadata:
    name: kibanadata

services:
  elasticsearch:
    image: elasticsearch:8.5.2
    container_name: es
    hostname: elastic
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: elastic
      KIBANA_PASSWORD: kibana
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      bootstrap.memory_lock: true
      xpack.security.enabled: false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic
  
  kibana:
    image: kibana:8.5.2
    container_name: kib
    hostname: kibana
    environment:
      SERVERNAME: kibana
      ELASTICSEARCH_URL: http://host.docker.internal:9200
      ELASTICSEARCH_HOSTS: '["http://host.docker.internal:9200"]'
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
networks:
  elastic:
    driver: bridge